#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

/* ES8311 音频编解码器 + NS4150B/ES8311 PA */
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// ES8311 使用 Duplex I2S 模式（注释掉下面一行启用简单模式，但 ES8311 需要 Duplex）
// #define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_3
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_9

#else

#define AUDIO_I2S_GPIO_MCLK    GPIO_NUM_5
#define AUDIO_I2S_GPIO_BCLK    GPIO_NUM_3
#define AUDIO_I2S_GPIO_WS      GPIO_NUM_4
#define AUDIO_I2S_GPIO_DOUT    GPIO_NUM_7
#define AUDIO_I2S_GPIO_DIN     GPIO_NUM_6

#endif

/* ES8311 codec I2C 引脚 */
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2

/* ES8311 PA 控制引脚（接 NS4150B SD 脚） */
#define AUDIO_CODEC_PA_PIN GPIO_NUM_8
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR  // AD0=GND → 0x18

/* 单麦配置，不需要声学参考声道回声消除 */
#define AUDIO_INPUT_REFERENCE    false

/* 本板无板载可控 LED（仅电源指示灯），板载按钮为 BOOT 键 */
#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

/* 1.77寸 ST7735S LCD（SPI3），背光 LEDA 常亮、无 GPIO 控制 */
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_MOSI_PIN      GPIO_NUM_17
#define DISPLAY_CLK_PIN       GPIO_NUM_18
#define DISPLAY_DC_PIN        GPIO_NUM_16
#define DISPLAY_RST_PIN       GPIO_NUM_15
#define DISPLAY_CS_PIN        GPIO_NUM_21

/* TF 卡（SDMMC 4-bit，GPIO matrix 引出；quad PSRAM 只占 GPIO26-32，不冲突） */
#define SD_CARD_MOUNT_POINT "/sdcard"
#define SDMMC_CMD_GPIO GPIO_NUM_35
#define SDMMC_CLK_GPIO GPIO_NUM_36
#define SDMMC_D0_GPIO  GPIO_NUM_37
#define SDMMC_D1_GPIO  GPIO_NUM_38
#define SDMMC_D2_GPIO  GPIO_NUM_33
#define SDMMC_D3_GPIO  GPIO_NUM_34


#ifdef CONFIG_LCD_ST7735_128X160
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  160
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#endif // _BOARD_CONFIG_H_